transformations:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      schema: dev
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev
