db-up:
	docker-compose --env-file ../config/local/.env --project-directory ../containers/postgres/docker-compose.yml up -d
db-down:
	docker-compose --env-file ../config/local/.env --project-directory ../containers/postgres/docker-compose.yml down